### ISSUE TITLE
FontAwesome Support

### ISSUE THREAD

**Issue by shoaibshakeel381** [gasparesganga/jquery-loading-overlay#1]
Can you please add support to fontawesome based loading indicators. So we can specify which icon to 
use as indicator.

**Comment by gasparesganga** [comment]
I will look into it, but my schedule is quite strict theese days. It may require a couple of weeks before I can work on it.

**Comment by gasparesganga** [comment]
Here you go, v1.1 is released with Font Awesome support included!

**Comment by shoaibshakeel381** [comment]
awesome. Thanks a lot.
