### ISSUE TITLE
resizing bug

### ISSUE THREAD

**Issue by ultim8me** [gasparesganga/jquery-loading-overlay#13]
there is resizing bug of the div overlay.. example code:

> var pages = ['main', 'users', 'settings'];
>   var contentDiv = $('#content');
>   $.each(pages, function(index, value) {
>     $('#' + value).click(function() {
>       contentDiv.LoadingOverlay("show");
>       $.post('...php', {
>         page:value
>       },
>       function(data) {
>         contentDiv.html(data);
>         contentDiv.LoadingOverlay("hide");
>       });
>     });
>   });

the #content has no css, and different data is loading to it, with different sizes. The overlay don't adopt to the size in right time, lets say first i get data one line then overlay is one line next time i get data in large size but the overlay is one line, next time i get data of one line but overlay is large size..

**Comment by gasparesganga** [comment]
What version of LoadingOverlay are you using?
What's the value of `resizeInterval ` option? Try to set `resizeInterval ` to `10`.

**Comment by ultim8me** [comment]
im using latest 1.5.3,  just tried resizeinterval 10 but with no changes i think the problem is my div with unknown dimensions, because first i call overlay then i show div and the div could be small or big

**Comment by gasparesganga** [comment]
You could try *showing* the div before calling LoadingOverlay (even if it's empty). It's supposed to work this way. What browser are you using?
Maybe you can provide a jsFiddle?

**Comment by gasparesganga** [comment]
I'm starting to get slightly annoyed by all those people opening *issues* and eventually leaving them just pending once they find out what they were doing wrong...
Is this your case as well? Do you have any update?

**Comment by maurorulli** [comment]
Tieni duro Gaspare!

**Comment by gasparesganga** [comment]
:-)

**Comment by gasparesganga** [comment]
Alright, still no answer. I guess you fixed your code. I'm closing this.
