### ISSUE TITLE
not work in jquery ajax option "async: false"

### ISSUE THREAD

**Issue by suwat-netprom** [gasparesganga/jquery-loading-overlay#15]
function getSuccessOutput() {
        $.LoadingOverlay("show"); // this loop infinity
        
        $.ajax({
            url:'test.php', // test.php return echo 'test call';
            async: false,
            complete: function (response) {
                $('#output').html(response.responseText); // response = 'test call'
            },
            error: function (data) {
                $('#output').html(data);
            },
        });
        $.LoadingOverlay("show");
        return false;
    }

**Comment by gasparesganga** [comment]
Would you care to elaborate a bit more, please?
How is this option even related to LoadingOverlay in first instance? Maybe you can show some relevant code?

**Comment by suwat-netprom** [comment]
**I change new code to this, it work**

function getSuccessOutput() {
        **$(document).ajaxStart(function(){
            $.LoadingOverlay("show");
        });**
        
        $.ajax({
            url:'test.php', // test.php return echo 'test call';
            async: false,
            complete: function (response) {
                $('#output').html(response.responseText); // response = 'test call'
            },
            error: function (data) {
                $('#output').html(data);
            },
        });

       **$(document).ajaxStop(function(){
            $.LoadingOverlay("hide");
        });**
        return false;
    }

my language is weak
**thank you**

**Comment by gasparesganga** [comment]
Ok, so does it now work as expected?
I'm sorry, this is **NOT** an issue related to LoadingOverlay, but rather a programming question. You can refer to [Example 5](https://gasparesganga.com/labs/jquery-loading-overlay/#example-5---display-a-loadingoverlay-during-each-ajax-request).
