### ISSUE TITLE
Update jsDelivr links

### ISSUE THREAD

**Issue by LukasDrgon** [gasparesganga/jquery-loading-overlay#17]
[jsDelivr switched to a fully automated system](https://www.jsdelivr.com/features), that can serve files from npm and GitHub. This means all future releases will be available automatically, but will use a new link structure.
I noticed you have some links at https://gasparesganga.com/labs/jquery-loading-overlay/, and just wanted to let you know, that for future versions the correct links are: 

- https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@latest/src/loadingoverlay.min.js
- https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@latest/extras/loadingoverlay_progress/loadingoverlay_progress.min.js

You can find links for all files at https://www.jsdelivr.com/package/npm/gasparesganga-jquery-loading-overlay.

I also noticed that this package doesn't have a default file set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`. This file will be displayed as the first/recommended link on our website.

Feel free to ping me if you have any questions regarding this change.

**Comment by gasparesganga** [comment]
Hi, thank you for letting me know about that.
That's great news, really!

I'll update all the links in my plugins documentation pages (I have several hosted on jsDelivr).
Just a question: I quickly went through your new documentation and it seems I don't even have to do anything to *publish a new package*? Will it be automatically be fetched from npm and/or github?

Cheers

PS: Yep, I'll add a default file as well, thanks for pointing this out.

**Comment by MartinKolarik** [comment]
@gasparesganga yep, everything on npm and GitHub is available without any action required from the author. We recommend using npm when possible, as npm packages are also searchable on our website.

**Comment by gasparesganga** [comment]
Great, thank you! 👍
