### ISSUE TITLE
Lag with jQuery Popup Overlay

### ISSUE THREAD

**Issue by ZiChuanBuXiu** [gasparesganga/jquery-loading-overlay#21]
Hi

I used your loading overlay in the jQuery Popup Overlay, which is in
`<script src="https://cdn.rawgit.com/vast-engineering/jquery-popup-overlay/1.7.13/jquery.popupoverlay.js"></script>`
It seems there is a little lag with the overlay when I scroll the Popup. I'm wondering if it is the Popup's issue or I made wrong configuration. I load the Loading Overlay with:
`$.LoadingOverlaySetup({
        color: "rgba(0, 0, 0, 0.8)",
        image: "images/something.gif",
        resizeInterval: 1
    });`

Thank you!

**Comment by gasparesganga** [comment]
It might be that value `1` for `resizeInterval`. It's definitely too low. I think an *extreme* setting would be `20`, but not less than that.
In order to verify if the lag depends on my plugin or something else, try to temporarily disable the auto resizing with `resizeInterval : false`.

**Comment by ZiChuanBuXiu** [comment]
Thanks for your reply! I tried it but it didn't work. I think it is the Popup's issue.

**Comment by gasparesganga** [comment]
I'll leave this here...
I don't mean to sound pretentious, but have you tried my [jQuery MessageBox](https://github.com/gasparesganga/jquery-message-box) plugin?
