### ISSUE TITLE
unable to use loadingoverlay in materialize modal 

### ISSUE THREAD

**Issue by mdrahiem** [gasparesganga/jquery-loading-overlay#22]
![image](https://user-images.githubusercontent.com/12086760/37612372-1086bc12-2bcb-11e8-8fa3-7b72cb6ead2e.png)

When I am trying to use loadingoverlay for .modal-content its looking like the above image. Instead when I am trying to use it for .modal its looking like below.

![image](https://user-images.githubusercontent.com/12086760/37612682-df76f064-2bcb-11e8-993f-ec10bf6874ac.png)

Can you please suggest me a solution for this. Thanks in Advance.

**Comment by gasparesganga** [comment]
Please provide some code or at least that Codepen you are using.

**Comment by mdrahiem** [comment]
sorry. I forgot. 

https://codepen.io/anon/pen/aYBQzE

**Comment by gasparesganga** [comment]
There was a bug lurking around for some time: if an element has `position : fixed` but also some margins, jQuery `.position()` fails to detect its actual position.
Fixed it with `getBoundingClientRect()`, your script should work with [v2.0.2](https://github.com/gasparesganga/jquery-loading-overlay/commit/01539ccd305340071311d27a0f74920bde0f2fcb), please give me some feedback.

**Comment by mdrahiem** [comment]
Hello. So far its been fixed for .modal but there is still problem with .modal-content. But anyways I can adjust with this. But if you can solve for that one as well, it would be great. 

Thanks much for quick reponses.

**Comment by mdrahiem** [comment]
![image](https://user-images.githubusercontent.com/12086760/37765025-30a726b0-2de9-11e8-8359-012388c2790f.png)

**Comment by gasparesganga** [comment]
That's the expected behaviour on your `.modal-content` element. You are seeing a bigger LoadingOverlay because that modal plugin you are using relies on `overflow  hidden` to hide part of the `.modal-content`.
LoadingOverlay is covering the `.modal-content` just as it is supposed to do.

Apply LoadingOverlay on `.modal` and you will be fine.

PS: No need to set `zindex`  option to `9999`, leave it the dafult value.

**Comment by mdrahiem** [comment]
Sure. Thanks much.
