### ISSUE TITLE
Fontawesome and text at the same time

### ISSUE THREAD

**Issue by rami85** [gasparesganga/jquery-loading-overlay#23]
Hi, 

is it possible set fontawesome and text together? I have tried bellow code:

```javascript
$.LoadingOverlay("show", {
            image: "",
            fontawesome: "fa fa-circle-o-notch fa-spin fa-fw loadingOverlaySpinner",
            text: "Loading...",
            maxSize: "100px"
        });
```

However it doesn't work. Any ideas? Thanks in advance.

**Comment by gasparesganga** [comment]
Of course it is possible. I don't know what you exactly mean with *it doesn't work*, but it actually does.
Maybe you just need to fix that `fa-circle-o-notch` class to `fa-circle-notch`?

Here is a working JSFiddle with your code: https://jsfiddle.net/mxvuqeu2/5/

**Comment by gasparesganga** [comment]
You're welcome.....
