### ISSUE TITLE
imageColor  not working

### ISSUE THREAD

**Issue by LebCit** [gasparesganga/jquery-loading-overlay#24]
Hello,

First of all tanks a lot for this beautiful, simple and powerful plugin.

I've tried to use the new defaults, as in example 5.
I've also tried to directly use the new defaults directly in `$.LoadingOverlay(action [,options])` without setting default options with `$.LoadingOverlaySetup(options)`.
In both case, inspecting the DOM show that the `div.loadingoverlay_element` has a `fill: rgb(0, 0, 0)` if i set the `imageColor` to `"#000"` or `"#000000"` or `"black"`, but nothing happens.

Going further in multiple `<svg>` file, I found that the `fill` attribute is applied to the `<svg>` tag directly or to the `<path>` tag or to the `<g>` tag off the image itself (not the stroke(s)).
So, if I set an `imageClass` to the image and target the tag that has the `fill` attribute and give it the desired fill color in a **CSS** file, everything goes as expected and the `fill` attribute has the defined color in **CSS** !

**EDIT / UPDATE**

If I do the following, I can control the fill and stroke(s) where ever they are in the `.svg` file : 
**JS**
`imageClass: "loadingoverlayimageclass"`
**CSS**
```
.loadingoverlayimageclass * {
    fill: red;
    stroke: black;
}
```
**END EDIT / UPDATE**

Hope that those information will help to tweak the plugin so the `fill` attribute will be applied to the exact `tag`.

Side Note : I'll be using your plugin in the next update of my theme that is already on the WP theme repository ;)

Thanks again for your time and all your efforts.

**Comment by gasparesganga** [comment]
Hi!
If I get it right, you are talking about a case where the SVG file has already some `fill` and/or `stroke` styles defined inline and we need to override them, right?

I assumed one has the *complete control* over the SVG file, thus he would use one without any inline style, or, in case there are some, he would set `imageColor` to `auto` and rely on them. But I think you are right, it makes sense to override them anyways with `imageColor` value.

Do you have any SVG file in particular to test? I can fix this right away.

**Comment by LebCit** [comment]
Hi,

No, I've tried it also on an `.svg` that has a `fill="none"`, same result when trying to set `imageColor` because the `fill` attribute is not directly in the `<svg>` tag but in a `<g>` tag that is a child of the `<svg>` tag. 

You can try any of those [SVG LOADERS](https://github.com/SamHerbert/SVG-Loaders)
Attached one, is one of them.

Thanks a lot :)
[ball-triangle.zip](https://github.com/gasparesganga/jquery-loading-overlay/files/1871954/ball-triangle.zip)

**Comment by gasparesganga** [comment]
Yep, that's what I wrote: those SVGs have inline styles built-in.
I will work-around that, don't worry.

**Comment by LebCit** [comment]
Hope that you'll also be able to target the stroke(s) some how.
Will then be able to style the `fill` and `stroke(s)` attributes.

Thanks a lot for your time :)

**Comment by LebCit** [comment]
Hello,

Can you please give me an example with a fiddle ?
The update works only on `fill` if I do : 
`imageColor: 'red'`
But if I try any of the following, nothing works : 
```
imageColor: {
    "fill": "red"
}
```
```
imageColor: {
    "fill": "red",
    "stroke": "black"
}
```
Thank you very much in advance for your help and your time.

**Comment by gasparesganga** [comment]
I'll release v2.1.0 today, please give me some time to update the documentation and you will find everything in there ;)

**Comment by gasparesganga** [comment]
Here you go, v2.1.0 has been released.
Find the info about upgraded `imageColor` option in the [documentation](https://gasparesganga.com/labs/jquery-loading-overlay/#imagecolor). Basically you can pass a two-elements array with *fill* and *stroke* colors respectively.
Cheers
