### ISSUE TITLE
Bug overlay not hiding

### ISSUE THREAD

**Issue by vankaiser** [gasparesganga/jquery-loading-overlay#25]
If LoadingOverlay("show") was called 2 x on the same element and you call LoadingOverlay("hide"), it will only hide the first overlay for that element.

**Comment by gasparesganga** [comment]
This is exactly the intended behaviour!
Have you **read the documentation** before opening an issue? There is stated multiple times that the *counter* feature is indeed a **feature**.
It allows great flexibility (look at examples 2 and 6 in the documentation) and if you want to *force* the hiding, simply set the `hide` parameter to `true`, again very well written in the documentation: [hide action](https://gasparesganga.com/labs/jquery-loading-overlay/#hide).

**Comment by vankaiser** [comment]
oops, didn't see the force option there. thanks for awesome plugin
