### ISSUE TITLE
overlays might colide when showing multiple

### ISSUE THREAD

**Issue by Hanmac** [gasparesganga/jquery-loading-overlay#26]
for Project reasons i can't use the global ajaxStart ones, and needed to use beforeSend and complete on the ajax request.
while that i noticed that if multiple ajax requests did try to call, it does show the overlay infinte time and it didn't go away after both ajax where finish.

Short look at the code shows this:
https://github.com/gasparesganga/jquery-loading-overlay/blob/master/dist/loadingoverlay.js#L220-L221
is that maybe wrong? 'data' is never defined at this place

does this maybe need this?

```javascript
if (typeof overlay !== "undefined") {
    data = overlay.data("loadingoverlay_data");
}
```

of using the _GetData Function:
```javascript
    var overlay = container.data("loadingoverlay");
    var data    = _GetData(overlay);
    if (data === false) {
    }
```

**Comment by gasparesganga** [comment]
Yep while you were commiting this I had already fixed it. My bad for introducing this silly bug in v2.1.1.
Thank you anyways!
