### ISSUE TITLE
use `$.inArray` instead of `array.indexOf`

### ISSUE THREAD

**Issue by shyangs** [gasparesganga/jquery-loading-overlay#28]
use `$.inArray` instead of `array.indexOf`

This better browser compatibility. For jQuery 1.x and IE8.

**Comment by gasparesganga** [comment]
I am sorry but I am **not** supporting IE8 (it isn't supposed to work with the heavy use of flexbox anyway).
I can change it in future releases since it won't affect the performances, but this does not guarantee IE8 compatibility at all.
