### ISSUE TITLE
can't import 'gasparesganga-jquery-loading-overlay' 

### ISSUE THREAD

**Issue by amsz** [gasparesganga/jquery-loading-overlay#30]
`package.json` main path is error: `"main": "dest/loadingoverlay.min.js"`

**Comment by gasparesganga** [comment]
Wow! This thing has been here for months and nobody, myself included, ever noticed it!
Thank you

**Comment by amsz** [comment]
Thanks. 
But NPM registry still 2.1.2, please publish it.

**Comment by gasparesganga** [comment]
Woaaahh I'm sorry, I completely forgot about that! It is published now

**Comment by amsz** [comment]
It worked fine in my webpack project, thanks again.
