### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by HamedFathi** [gasparesganga/jquery-loading-overlay#32]
Is it possible for you to release a version without jquery as a dependency?

Nowadays developers use Aurelia, Vue, Angular for their projects and don't need jquery.

**Comment by gasparesganga** [comment]
Are you really asking to remove jQuery dependency from a ***jQuery** plugin*? Ok, it was an easy joke, now seriously ;)

Those frameworks are cool, Angular is well established and Vue is gaining moment (don't know about Aurelia to be honest), but their purpose is definitely different than jQuery.
They are great when it comes to build a *reactive* app with a solid foundation in an easy way, but they cannot really **replace** jQuery in many use cases (at least in my view).

Now, having said that, I understand your question is actually about releasing this *jQuery plugin* without jQuery dependency, hence being a *vanilla javascript library*. While it could certainly be possible, the effort needed to maintain all the features and browsers compatibility without jQuery is absolutely out of the original scope, I'm sorry.

Maybe I could think about a very basic version, something very straightforward but still functional that would satisfy the most common use case(s) without bringing all the complexity of the original plugin. What features would you consider essential?

**Comment by HamedFathi** [comment]
Hello @gasparesganga 

I know about all of them. Let's say. [Aurelia](http://aurelia.io) is awesome and addictive I suggest it to you. we are working on [AureliaToolbelt](https://github.com/aurelia-toolbelt/aurelia-toolbelt) you can find the demo [here](https://aurelia-toolbelt.github.io)

We think your plugin is very cool and far better than [jQuery BlockUI](http://malsup.com/jquery/block/)
I want to replace [our BlockUI component](https://aurelia-toolbelt.github.io/#/jquery/blockui) with your cool library.

AureliaToolbelt is based on Bootstrap 4 and BS4 will [remove jQuery](https://github.com/twbs/bootstrap/pull/23586) in version 4.3

We want to use native js libraries for removing jQuery in future. This is the reason that I asked for native one.

**Comment by gasparesganga** [comment]
I'm glad you appreciate my plugin, but for the time being it will stay as is, a *jQuery* plugin.

If you look at the code you will see that some crucial parts are not using jQuery at all for better performaces, but what jQuery brings and is absolutely dependable is browser compatibility.
For example, nowadays I (and I guess most developers) don't go crazy about CSS hacks, prefixes and browser specific properties, I either use Autoprefixer or simply rely on jQuery if I'm injecting CSS through JS (this is the case with this plugin). Imagine how complicated would be maintaining the same level of compatibility with vanilla JS. Hundreds of issues and requests guaranteed in no time! :)

Maybe in the future this may change, you'll never know.
