### ISSUE TITLE
Overlay hiding not working when using both AjaxStart and custom svg file

### ISSUE THREAD

**Issue by lvmajor** [gasparesganga/jquery-loading-overlay#33]
How to reproduce:

1. As mentioned in the docs, set the Ajax requests to trigger the loadingOverlay
```
$(document).ajaxStart(function(){
    $.LoadingOverlay("show");
});
$(document).ajaxStop(function(){
    $.LoadingOverlay("hide");
});
```
2. Then in a custom jquery/javascript function, for example in my case on a button click, trigger the loadingOverlay 
```
$.LoadingOverlay("show"); 
```
3. When the request ends and you want to close the overlay, simply call:
```
$.LoadingOverlay("hide");
```

**Expected behavior:** Close the overlay
**Observed behavior:** The overlay is not hidden correctly

In fact, the problem is that 2 instances of the overlay are created. One for custom request which creates a new overlay, which is fine as we call the `$.LoadingOverlay("show");`, and another one caused by the AjaxStart event, triggered by the SVG file  [`element.load()` ](https://github.com/gasparesganga/jquery-loading-overlay/blob/3c95e8ac3acdcfa7fe97fc95e5e0ca055f4389d0/src/loadingoverlay.js#L278) call

**Comment by lvmajor** [comment]
I saw in previous issues that having multiple instances is a feature, but in this case it doesn't seem to be by design that the overlay does not close correctly. 

I also tried with the force option, sadly to no avail.

**Comment by gasparesganga** [comment]
I don't understand this part and how is it related with the main question:

> Then in a custom jquery/javascript function, for example in my case on a button click, trigger the loadingOverlay

Does it mean you are effectively calling `$.LoadingOverlay("show");` from another part of your code other than `$(document).ajaxStart()`?

**Comment by lvmajor** [comment]
Yes that's exactly it. I am manually calling it from a button click handler

**Comment by lvmajor** [comment]
But the fact that the svg is being loaded from an Ajax call also triggers the AjaxStart overlay generation. Then when the request ends, one instance is correctly removed from the Dom, the other one remains

**Comment by gasparesganga** [comment]
Ok, it seems this is happening when you have binded an LoadingOverlay *show* method to `AjaxStart` **AND** you are using a custom image.
<del>It's actually a complex bug to fix</del>, but I am currently looking into that.

Kudos for noticing that, it's something I have introduced with v2 and I hadn't thought of at all!

**Comment by gasparesganga** [comment]
That turned out to be an easier fix than expected. jQuery's parameter `global` for Ajax method came in handy.
I will release the patched version in a few minutes.

**Comment by lvmajor** [comment]
Glad I could help a bit :) Thanks for the quick patch!
