### ISSUE TITLE
Loader hides in early stage.

### ISSUE THREAD

**Issue by salmanalikhan** [gasparesganga/jquery-loading-overlay#38]
I am using multiple loaders (one for each backend call) in component based scenario. In my case I have 3 loaders and they are being shown and hidden subsequently, but the last loader doesn't show up. I think the 2nd or first loader's hide method interferes with the show method of other one.

I have also tried by putting console log on data.count on show and hide method. I see that it misses to decrease the counter in last attempt.

The version I am using is : 2.1.6

**Comment by gasparesganga** [comment]
Are you showing them on the same target?
Please provide some code or link where I can see this behaviour, otherwise I cannot help you.

**Comment by KA24956T** [comment]
While hiding the target div or parent div then loading is still visible. Please provide the solution.

**Comment by gasparesganga** [comment]
Any update on that?

**Comment by gasparesganga** [comment]
Alright, I assume there was some issue on your side which is now fixed... It is always a nice thing to do to close opened issues once you have found a solution though...
