### ISSUE TITLE
While hiding the target div or parent div then loading is still visible. Please provide the solution.

### ISSUE THREAD

**Issue by KA24956T** [gasparesganga/jquery-loading-overlay#39]
While hiding the target div or parent div then loading is still visible. Please provide the solution.

**Comment by gasparesganga** [comment]
Please provide some example code which shows the behaviour, then I will eventually be able to work out a solution

**Comment by gasparesganga** [comment]
Any update?

**Comment by gasparesganga** [comment]
Nothing? Then I guess you fixed something on your side and this wasn't caused by LoadingOverlay... I'm closing this...
