### ISSUE TITLE
howto with modal

### ISSUE THREAD

**Issue by stefanKBL** [gasparesganga/jquery-loading-overlay#4]
thanks, works great, but not with a modal bootstrap, even with element id. Any idea ?
thanks.

**Comment by gasparesganga** [comment]
Can you provide some sort of "example playground" to replicate your situation so I can check and eventually find a solution?
You could create a repository to clone for example.

**Comment by gasparesganga** [comment]
You haven't replied for more than a month, I can't do anything but close the issue.
