### ISSUE TITLE
Wouldn't Load when sending email thru Ajax

### ISSUE THREAD

**Issue by bhaviljain68** [gasparesganga/jquery-loading-overlay#43]
Hi, I'm still learning to code.

I have a code where an ajax request is made to a PHP function and if the function succeeds, then an email is sent from within the said function.

I tried to implement this library and it works properly on all other ajax calls except this one.
I tried 3 methods
1. By Manually invoking $.LoadingOverlay("show") and $.LoadingOverlay("hide")
2. Via ajaxStart() and ajaxStop().
3. Via ajaxSend() and ajaxComplete()

The problem is, sending mails takes time and the overlay wouldn't start on the button click, it would show at the very end when the email is sent even if I manually trigger the overlay before the $.ajax({}); starts.

I'm not sure if I'm making a mistake, or maybe my concept of ajax is wrong. 
But isn't the overlay/ajax call supposed to start when the user clicks a button and end when the task is completed?

I apologise in advance if this is a stupid question

**Comment by gasparesganga** [comment]
You asked the same question [here](http://disq.us/p/25tgm2x)...
