### ISSUE TITLE
Any sample html page to customize and see different options

### ISSUE THREAD

**Issue by Github743** [gasparesganga/jquery-loading-overlay#47]
I tried to create one html page and modify few things but couldn't. Any demo page instead of the default one provided

**Comment by gasparesganga** [comment]
Hi. I am afraid I cannot quite get the issue here. Are you looking for a demo page to showcase all the features and possibilities of this plugin?
Then in the official documentation page there is exactly what you are looking for, see [Example 4 - Complete playground](https://gasparesganga.com/labs/jquery-loading-overlay/#example-4---complete-playground).

Just a note: my website is cookie-free (_yep, I dare everyone find a website with NO cookies these days, not even Google Analytics!_), no ads, no trackes, nothing at all. I don't see why you wouldn't use it.

**Comment by Github743** [comment]
I tried to integrate but some how it is not working in my application, not sure what I am missing. Also instead of the circular one can I use my own SVG?

**Comment by Github743** [comment]
Thanks I was but confused working now

**Comment by Github743** [comment]
How can we align text next to image there is a gap

![image](https://user-images.githubusercontent.com/3626755/146413740-254e753a-51f7-4296-bbd8-5884db54e24d.png)

**Comment by gasparesganga** [comment]
> Also instead of the circular one can I use my own SVG?

Sure, the `image` option is there exactly for that. Please refer to the official documentation page for questions like that.

> How can we align text next to image there is a gap

You can try playing with some custom CSS, using `imageClass` and/or `textClass` options, or go for a 100% custom route with a custom element (_ie: a div containing both the image and the text_), see `custom` property.

**Comment by Github743** [comment]
Hmm looks like this we need to change a bit, `$this.css("font-size", (size * resizeFactor) + data.settings.size.units);` but not knowing what to do. I tried with different options no luck

**Comment by Github743** [comment]
Also is it possible to achieve the progress with the image? I would like to animate the image to move from left to right?

**Comment by gasparesganga** [comment]
Honestly I cannot see hot changing the `font-size` computing logic would help with positioning.

About the second question, unfortunately the answer is no. Right now the _progress_ capabilities are limited to a progress bar.
You could always program it yourself and wrap it in a `custom` element if ou really wanted to.

Right now this library is in _maintenance mode_ until I get enough time to publish a new major release, which requires a complete rewriting. This means that I will address any bug it might come out but I won't add any new feature before that aforementioned new major release, I'm sorry.
