### ISSUE TITLE
Importing by vite.

### ISSUE THREAD

**Issue by ivose** [gasparesganga/jquery-loading-overlay#49]
Maybe you can write proper instructions how to install also with vite. E.g "npm install gasparesganga-jquery-loading-overlay", in a laravel's resources/js/app.js "import ??? from gasparesganga-jquery-loading-overlay" and what to do with the imported staff? I long time try one and another thing. chrome console starts to display "error jquery doesnt exist".

**Comment by gasparesganga** [comment]
Sorry but I don't get what you mean with *proper instructions*...
Have you read the [official documentation](https://gasparesganga.com/labs/jquery-loading-overlay/)?
Of course you can use npm exactly like that and then it's just a matter of including the JS file **after** jQuery, as simple as that.

I have no idea about any specific Laravel requirements, I am not using it. Anyways, it should work as any other jQuery plugin. Simply include the single `loadingoverlay.min.js` file ***after*** jQuery and you're good to go.
If your browser is complaining about jQuery not existing, probably you have not included jQuery before using it with a plugin or your code.

**Comment by gasparesganga** [comment]
Somehow it does not surprise me that someone who asks for *proper instructions* (I put a lot of effort in writing the official documentation) doesn't even bother getting back after I took my time to answer his question which indeed was **NOT** related to the plugin in the first place...

Good luck.
