### ISSUE TITLE
More Options

### ISSUE THREAD

**Issue by Bernd2069** [gasparesganga/jquery-loading-overlay#6]
There are a lot of fixed parameters, for example the position of the image.
Please enable more parameters like imageposition, because if the element is a long list the image is not shown

**Comment by gasparesganga** [comment]
What do you mean with _"the element is a long list"_? Are you talking about an element which overflows the current viewport?
If that's the case, I hadn't thought about that. I can certainly expose that option.
What other parameters are you referring to? Please try to give me some details and I will work on it.
It sounds like an easy fix ;)

**Comment by Bernd2069** [comment]
You are right, my "div" element overflows the screen. So I think you can make a little change like
Line 74: "background-position"   : "center center",
Replace 74: "background-position"   : settings.imageposition,
Add after Line 19: imageposition   : "top center" 

So I have an option to place the image. Sorry my Javascript knowledge is  poor.

**Comment by gasparesganga** [comment]
Here you go. I've just committed (378a2f5) Version 1.4.0, which includes an **imagePosition** option.
It is passed to the CSS _background-position_ property, as you requested.
Note that values like `"center 100px"` are valid and accepted as well.

Before actually creating a release, I'm adding support for a CDN and need to update the documentation, but you can download the updated code even now from the master branch.

**EDIT :** Version [1.4.0](https://github.com/gasparesganga/jquery-loading-overlay/releases/tag/1.4.0) has been released.
