### ISSUE TITLE
Bug when resize window

### ISSUE THREAD

**Issue by SeppJorgen** [gasparesganga/jquery-loading-overlay#9]
Hi, great plugin! Unfortunately I noticed you have a small bug in feature  _single element overlay_, when you resize window browser(or do screen rotation on your phone/tablet) while overlay is visible then the overlay does not change with the element. It could be a problem because elements under the overlay are clickable and also It does not look nice.

**Comment by gasparesganga** [comment]
It seems it'm more a _position-related_ problem and not strictly a resize one. Do you have any code/testcase ready where I can test and fix the problem?

**Comment by SeppJorgen** [comment]
Testcase is ready on [your own demo page](http://gasparesganga.com/labs/jquery-loading-overlay/#example-2---single-element-overlay). I did not try on my own web cause I suppose you have same source code on Github as on the demo page. 
I had same problem in my plugin and only solution I have found was through the Javascript. You need to dynamic resize the overlay element by bind code on window event `resize`.

**Comment by gasparesganga** [comment]
Ok, I'll see what I can do. Actually I don't think windows's resize event is relevant here, it's likely to be related to the fixed positioning.
I will probably release a fix in a couple of days, thanks for your feedback!

**Comment by SeppJorgen** [comment]
Great, thanks!
Just from my experience, the fix only with CSS positioning will not solve the case when you have element which is scrollable under some size (It is really often I think for example tables) then the no scrolled part will not covered by overlay.

**Comment by gasparesganga** [comment]
Here you go, I've fixed it for good with [v1.4.1](https://github.com/gasparesganga/jquery-loading-overlay/releases/tag/v1.4.1).
Thanks for signaling me the bug ;)
